INSERT INTO Ingredients (menu_item_name, ingredient_name, quantity, unit) VALUES
('Classic Milk Tea', 'Black Tea Base', 1.0, 'cup'),
('Classic Milk Tea', 'Milk Powder', 2.0, 'tbsp'),
('Classic Milk Tea', 'Sugar Syrup', 1.0, 'oz'),
('Classic Milk Tea', 'Ice', 1.0, 'scoop'),
('Classic Milk Tea', 'Cup', 1.0, 'pc'),
('Classic Milk Tea', 'Lid', 1.0, 'pc'),
('Classic Milk Tea', 'Straw', 1.0, 'pc'),

('Ginger Tea', 'Ginger Syrup', 1.5, 'oz'),
('Ginger Tea', 'Hot Water', 1.0, 'cup'),
('Ginger Tea', 'Cup', 1.0, 'pc'),
('Ginger Tea', 'Lid', 1.0, 'pc'),

('Matcha with Fresh Milk', 'Matcha Powder', 1.5, 'tsp'),
('Matcha with Fresh Milk', 'Fresh Milk', 1.0, 'cup'),
('Matcha with Fresh Milk', 'Sugar Syrup', 1.0, 'oz'),
('Matcha with Fresh Milk', 'Ice', 1.0, 'scoop'),
('Matcha with Fresh Milk', 'Cup', 1.0, 'pc'),
('Matcha with Fresh Milk', 'Lid', 1.0, 'pc'),
('Matcha with Fresh Milk', 'Straw', 1.0, 'pc'),

('Mango Green Tea', 'Green Tea Base', 1.0, 'cup'),
('Mango Green Tea', 'Mango Syrup', 1.5, 'oz'),
('Mango Green Tea', 'Ice', 1.0, 'scoop'),
('Mango Green Tea', 'Cup', 1.0, 'pc'),
('Mango Green Tea', 'Lid', 1.0, 'pc'),
('Mango Green Tea', 'Straw', 1.0, 'pc'),

('Mango Mojito', 'Mango Syrup', 1.5, 'oz'),
('Mango Mojito', 'Lime Juice', 0.5, 'oz'),
('Mango Mojito', 'Mint Leaves', 3.0, 'leaves'),
('Mango Mojito', 'Soda Water', 1.0, 'cup'),
('Mango Mojito', 'Ice', 1.0, 'scoop'),
('Mango Mojito', 'Cup', 1.0, 'pc'),
('Mango Mojito', 'Lid', 1.0, 'pc'),

('Honey Tea', 'Black Tea Base', 1.0, 'cup'),
('Honey Tea', 'Honey Syrup', 1.5, 'oz'),
('Honey Tea', 'Ice', 1.0, 'scoop'),
('Honey Tea', 'Cup', 1.0, 'pc'),
('Honey Tea', 'Lid', 1.0, 'pc'),

('Coffee Ice Blended with Ice Cream', 'Coffee Concentrate', 1.5, 'oz'),
('Coffee Ice Blended with Ice Cream', 'Vanilla Ice Cream', 1.0, 'scoop'),
('Coffee Ice Blended with Ice Cream', 'Ice', 1.0, 'scoop'),
('Coffee Ice Blended with Ice Cream', 'Milk', 0.5, 'cup'),
('Coffee Ice Blended with Ice Cream', 'Cup', 1.0, 'pc'),
('Coffee Ice Blended with Ice Cream', 'Dome Lid', 1.0, 'pc'),
('Coffee Ice Blended with Ice Cream', 'Thick Straw', 1.0, 'pc'),

('Thai Pearl Milk Tea', 'Thai Tea Base', 1.0, 'cup'),
('Thai Pearl Milk Tea', 'Condensed Milk', 1.0, 'oz'),
('Thai Pearl Milk Tea', 'Tapioca Pearls', 1.0, 'scoop'),
('Thai Pearl Milk Tea', 'Ice', 1.0, 'scoop'),
('Thai Pearl Milk Tea', 'Cup', 1.0, 'pc'),
('Thai Pearl Milk Tea', 'Lid', 1.0, 'pc'),
('Thai Pearl Milk Tea', 'Straw', 1.0, 'pc'),

('Creama Tea', 'Green Tea Base', 1.0, 'cup'),
('Creama Tea', 'Creama Topping', 1.0, 'scoop'),
('Creama Tea', 'Ice', 1.0, 'scoop'),
('Creama Tea', 'Cup', 1.0, 'pc'),
('Creama Tea', 'Lid', 1.0, 'pc'),

('Peach Mojito', 'Peach Syrup', 1.5, 'oz'),
('Peach Mojito', 'Lime Juice', 0.5, 'oz'),
('Peach Mojito', 'Mint Leaves', 3.0, 'leaves'),
('Peach Mojito', 'Soda Water', 1.0, 'cup'),
('Peach Mojito', 'Ice', 1.0, 'scoop'),
('Peach Mojito', 'Cup', 1.0, 'pc'),
('Peach Mojito', 'Lid', 1.0, 'pc'),

('Cocoa Lover with Fresh Milk', 'Cocoa Powder', 2.0, 'tbsp'),
('Cocoa Lover with Fresh Milk', 'Fresh Milk', 1.0, 'cup'),
('Cocoa Lover with Fresh Milk', 'Sugar Syrup', 1.0, 'oz'),
('Cocoa Lover with Fresh Milk', 'Ice', 1.0, 'scoop'),
('Cocoa Lover with Fresh Milk', 'Cup', 1.0, 'pc'),
('Cocoa Lover with Fresh Milk', 'Lid', 1.0, 'pc'),
('Cocoa Lover with Fresh Milk', 'Straw', 1.0, 'pc'),

('Oreo Ice Blended with Pearl', 'Oreo Crumbs', 2.0, 'tbsp'),
('Oreo Ice Blended with Pearl', 'Milk', 1.0, 'cup'),
('Oreo Ice Blended with Pearl', 'Tapioca Pearls', 1.0, 'scoop'),
('Oreo Ice Blended with Pearl', 'Ice', 1.0, 'scoop'),
('Oreo Ice Blended with Pearl', 'Cup', 1.0, 'pc'),
('Oreo Ice Blended with Pearl', 'Dome Lid', 1.0, 'pc'),
('Oreo Ice Blended with Pearl', 'Thick Straw', 1.0, 'pc');